type ChapterNumbers =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 31
  | 32
  | 33
  | 34
  | 35
  | 36
  | 37
  | 38
  | 39
  | 40
  | 41
  | 42
  | 43
  | 44
  | 45
  | 46
  | 47
  | 48
  | 49
  | 50
  | 51
  | 52
  | 53
  | 54
  | 55
  | 56
  | 57
  | 58
  | 59
  | 60
  | 61
  | 62
  | 63
  | 64
  | 65
  | 66
  | 67
  | 68
  | 69
  | 70
  | 71
  | 72
  | 73
  | 74
  | 75
  | 76
  | 77
  | 78
  | 79
  | 80
  | 81
  | 82
  | 83
  | 84
  | 85
  | 86
  | 87
  | 88
  | 89
  | 90
  | 91
  | 92
  | 93
  | 94
  | 95
  | 96
  | 97
  | 98
  | 99
  | 100
  | 101
  | 102
  | 103
  | 104
  | 105
  | 106
  | 107
  | 108
  | 109
  | 110
  | 111
  | 112
  | 113
  | 114;

type ChapterNames =
  | "al-Fātihah"
  | "al-Baqarah"
  | "Āl-ʿImrān"
  | "an-Nisāʾ"
  | "al-Māʾidah"
  | "al-Anʿām"
  | "al-Aʿrāf"
  | "al-Anfāl"
  | "at-Taubah"
  | "Yūnus"
  | "Hūd"
  | "Yūsuf"
  | "ar-Raʿd"
  | "Ibrāhīm"
  | "al-Ḥijr"
  | "an-Naḥl"
  | "al-Isrāʾ"
  | "al-Kahf"
  | "Maryam"
  | "Ṭā-Hā"
  | "al-Anbiyāʾ"
  | "al-Ḥajj"
  | "al-Muʾminūn"
  | "an-Nūr"
  | "al-Furqān"
  | "ash-Shuʿarā"
  | "an-Naml"
  | "al-Qaṣaṣ"
  | "al-ʿAnkabūt"
  | "ar-Rūm"
  | "Luqmān"
  | "as-Sajdah"
  | "al-Aḥzāb"
  | "Sabaʾ"
  | "Fāṭir"
  | "Yā-Sīn"
  | "as-Ṣāffāt"
  | "Ṣād"
  | "az-Zumar"
  | "Ghāfir"
  | "Fuṣṣilat"
  | "ash-Shūrā"
  | "az-Zukhruf"
  | "ad-Dukhān"
  | "al-Jāthiyah"
  | "al-Aḥqāf"
  | "Muḥammad"
  | "al-Fatḥ"
  | "al-Ḥujurāt"
  | "Qāf"
  | "adh-Dhāriyāt"
  | "at-Ṭūr"
  | "an-Najm"
  | "al-Qamar"
  | "ar-Raḥmān"
  | "al-Wāqiʿah"
  | "al-Ḥadīd"
  | "al-Mujādilah"
  | "al-Ḥashr"
  | "al-Mumtaḥanah"
  | "as-Ṣaff"
  | "al-Jumuʿah"
  | "al-Munāfiqūn"
  | "at-Taghābun"
  | "at-Ṭalāq"
  | "at-Taḥrīm"
  | "al-Mulk"
  | "al-Qalam"
  | "al-Ḥāqqah"
  | "al-Maʿārij"
  | "Nūḥ"
  | "al-Jinn"
  | "al-Muzzammil"
  | "al-Muddaththir"
  | "al-Qiyāmah"
  | "al-Insān"
  | "al-Mursalāt"
  | "an-Nabaʾ"
  | "an-Nāziʿāt"
  | "ʿAbasa"
  | "at-Takwīr"
  | "al-Infiṭār"
  | "al-Muṭaffifīn"
  | "al-Inshiqāq"
  | "al-Burūj"
  | "at-Ṭāriq"
  | "al-Aʿlā"
  | "al-Ghāshiyah"
  | "al-Fajr"
  | "al-Balad"
  | "ash-Shams"
  | "al-Layl"
  | "ad-Ḍuḥā"
  | "ash-Sharḥ"
  | "at-Tīn"
  | "al-ʿAlaq"
  | "al-Qadr"
  | "al-Bayyinah"
  | "az-Zalzalah"
  | "al-ʿĀdiyāt"
  | "al-Qāriʿah"
  | "at-Takāthur"
  | "al-ʿAsr"
  | "al-Humazah"
  | "al-Fīl"
  | "Quraysh"
  | "al-Māʿūn"
  | "al-Kawthar"
  | "al-Kāfirūn"
  | "an-Naṣr"
  | "al-Masad"
  | "al-Ikhlāṣ"
  | "al-Falaq"
  | "an-Nās";

const ChapterNamesToNumberMap = {
  "al-Fātihah": 1,
  "al-Baqarah": 2,
  "Āl-ʿImrān": 3,
  "an-Nisāʾ": 4,
  "al-Māʾidah": 5,
  "al-Anʿām": 6,
  "al-Aʿrāf": 7,
  "al-Anfāl": 8,
  "at-Taubah": 9,
  Yūnus: 10,
  Hūd: 11,
  Yūsuf: 12,
  "ar-Raʿd": 13,
  Ibrāhīm: 14,
  "al-Ḥijr": 15,
  "an-Naḥl": 16,
  "al-Isrāʾ": 17,
  "al-Kahf": 18,
  Maryam: 19,
  "Ṭā-Hā": 20,
  "al-Anbiyāʾ": 21,
  "al-Ḥajj": 22,
  "al-Muʾminūn": 23,
  "an-Nūr": 24,
  "al-Furqān": 25,
  "ash-Shuʿarā": 26,
  "an-Naml": 27,
  "al-Qaṣaṣ": 28,
  "al-ʿAnkabūt": 29,
  "ar-Rūm": 30,
  Luqmān: 31,
  "as-Sajdah": 32,
  "al-Aḥzāb": 33,
  Sabaʾ: 34,
  Fāṭir: 35,
  "Yā-Sīn": 36,
  "as-Ṣāffāt": 37,
  Ṣād: 38,
  "az-Zumar": 39,
  Ghāfir: 40,
  Fuṣṣilat: 41,
  "ash-Shūrā": 42,
  "az-Zukhruf": 43,
  "ad-Dukhān": 44,
  "al-Jāthiyah": 45,
  "al-Aḥqāf": 46,
  Muḥammad: 47,
  "al-Fatḥ": 48,
  "al-Ḥujurāt": 49,
  Qāf: 50,
  "adh-Dhāriyāt": 51,
  "at-Ṭūr": 52,
  "an-Najm": 53,
  "al-Qamar": 54,
  "ar-Raḥmān": 55,
  "al-Wāqiʿah": 56,
  "al-Ḥadīd": 57,
  "al-Mujādilah": 58,
  "al-Ḥashr": 59,
  "al-Mumtaḥanah": 60,
  "as-Ṣaff": 61,
  "al-Jumuʿah": 62,
  "al-Munāfiqūn": 63,
  "at-Taghābun": 64,
  "at-Ṭalāq": 65,
  "at-Taḥrīm": 66,
  "al-Mulk": 67,
  "al-Qalam": 68,
  "al-Ḥāqqah": 69,
  "al-Maʿārij": 70,
  Nūḥ: 71,
  "al-Jinn": 72,
  "al-Muzzammil": 73,
  "al-Muddaththir": 74,
  "al-Qiyāmah": 75,
  "al-Insān": 76,
  "al-Mursalāt": 77,
  "an-Nabaʾ": 78,
  "an-Nāziʿāt": 79,
  ʿAbasa: 80,
  "at-Takwīr": 81,
  "al-Infiṭār": 82,
  "al-Muṭaffifīn": 83,
  "al-Inshiqāq": 84,
  "al-Burūj": 85,
  "at-Ṭāriq": 86,
  "al-Aʿlā": 87,
  "al-Ghāshiyah": 88,
  "al-Fajr": 89,
  "al-Balad": 90,
  "ash-Shams": 91,
  "al-Layl": 92,
  "ad-Ḍuḥā": 93,
  "ash-Sharḥ": 94,
  "at-Tīn": 95,
  "al-ʿAlaq": 96,
  "al-Qadr": 97,
  "al-Bayyinah": 98,
  "az-Zalzalah": 99,
  "al-ʿĀdiyāt": 100,
  "al-Qāriʿah": 101,
  "at-Takāthur": 102,
  "al-ʿAsr": 103,
  "al-Humazah": 104,
  "al-Fīl": 105,
  Quraysh: 106,
  "al-Māʿūn": 107,
  "al-Kawthar": 108,
  "al-Kāfirūn": 109,
  "an-Naṣr": 110,
  "al-Masad": 111,
  "al-Ikhlāṣ": 112,
  "al-Falaq": 113,
  "an-Nās": 114,
};

export { ChapterNumbers, ChapterNames, ChapterNamesToNumberMap };
